---
name: CI
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  repo-lint:
    name: Repository Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ibiqlik/action-yamllint@v3.1.0
        with:
          file_or_dir: .
          strict: true
          no_warnings: false
          config_file: .yamllint
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        env:
          SHELLCHECK_OPTS: -s bash
        with:
          format: tty
